stages :
  - pre-build
  - build

init:
  stage: pre-build
  image: ubuntu-latest
  script: apt update && apt-get install -y cmake libwxgtk3.0-gtk3-dev

project:
  stage : build
  script :
    - mkdir cmake-build-debug
    - cd cmake-build-debug
    - cmake .. && cmake --build . && make
