/**
 * @file ids.h
 * @author Haoxiang Zhang
 *
 *
 */

#ifndef SPARTYGNOME_IDS_H
#define SPARTYGNOME_IDS_H

/**
 * Menu id values
 */
enum IDs{
    IDM_ADDPLATFORM1 = wxID_HIGHEST + 1,
    IDM_ADDPLATFORM2,
    IDM_ADDPLATFORM3,
    IDM_ADDPLATFORM4, IDM_ADDSPARTYGNOME, IDM_ADDLEVEL1,
    IDM_ADDLEVEL2, IDM_ADDLEVEL3, IDM_ADDLEVEL0
};
#endif //SPARTYGNOME_IDS_H
